<!-- SPDX-License-Identifier: GPL-3.0-only -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Hibiki.DesktopPreview</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\control-model\Hibiki.ControlModel.csproj" />
  </ItemGroup>
</Project>
